print('How does NASA organize their company parties?')
input()
print('they planet''\n')
print('What kind of shoes do ninjas wear?')
input()
print('sneakers''\n')
print('you want to hear a pizza joke?')
input()
print('Nevermind it\'s pretty Cheesy')
